name: Publish Docker image

on:
  push:
    branches:
      - 'test'
  release:
    types: [published]

jobs:
  build_and_push:
   name: Build and Push Docker image to Docker Hub
   runs-on: ubuntu-latest
   permissions:
     packages: write
     contents: read
     attestations: write
     id-token: write
   env:
     DOCKER_USERNAME: 'watahari'
     IMAGE_NAME: 'prometheus-dyson-exporter'
     NAMESPACE: 'watahari'
     REGISTRY: 'docker.io'
   steps:
    - name: Check Out prometheus-dyson-exporter Repo 
      uses: actions/checkout@v4.2.2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ${{ env.NAMESPACE }}/${{ env.IMAGE_NAME}}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
